"""add relationship between table

Revision ID: 655d1a30e355
Revises: af9d3bbfe5f6
Create Date: 2024-02-20 10:32:14.178843

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "655d1a30e355"
down_revision = "af9d3bbfe5f6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("cafe", schema=None) as batch_op:
        batch_op.add_column(sa.Column("author_id", sa.Integer(), nullable=True))
        batch_op.create_foreign_key("author_id_fn", "users", ["author_id"], ["id"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("cafe", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_column("author_id")

    # ### end Alembic commands ###
